server:
  port: 8082

spring:
  datasource:
    #url: jdbc:h2:mem:varenichnaya-db
    # save in ==> project-root/data/
    url: jdbc:h2:file:./data/varenichnaya-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    "[org.hibernate.SQL]": debug